Vagrant.configure("2") do |config|
  config.vm.box = "ebarriosjr/FreeBSD12.1-zfs"
  config.vm.box_version = "0.0.1"
  
  # config.vm.network "private_network", ip: "192.168.33.10"
  
  # config.vm.network "public_network"

  # config.vm.synced_folder "../data", "/vagrant_data"

  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
    config.vm.provider :libvirt do |v|
        v.memory = 4096
    end

  config.vm.provision "shell", inline: <<-SHELL
    pkg install -y python
  SHELL

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
    ansible.become = true
  end
  
end
